# LATIHAN ARRAY

In [1]:
# perkalian matriks array

import numpy as np

A = np.array([[[16, 7, 2005]]])
B = np.array([[71, 7, 14]])

kali = A * B
print(kali)

[[[ 1136    49 28070]]]


In [2]:
# pengurangan matriks array

import numpy as np

A = np.array([[[16, 7, 2005]]])
B = np.array([[71, 7, 14]])

kurang = A - B
print(kurang)

[[[ -55    0 1991]]]


In [3]:
# tranpose matrix array

import numpy as np 

A = np.array([[16,7,2005],[71,7,14]])

transpose_A = np.transpose(A)
print(transpose_A)

[[  16   71]
 [   7    7]
 [2005   14]]


In [4]:
# inverse matriks array

import numpy as np

A = np.array([[16,7] , [7,14]])

inverse_A = np.linalg.inv(A)
print("\n invers matriks A:")
print(inverse_A)


 invers matriks A:
[[ 0.08       -0.04      ]
 [-0.04        0.09142857]]


In [5]:
# determinant matiks array

import numpy as np

A = np.array([[16,7],[7,14]])

determinant_A = np.linalg.det(A)
print("determinant dari matriks A:",determinant_A)

determinant dari matriks A: 175.00000000000006
